Added android functionality
hashcube/kochava pull request #2
Opened 2016-09-27 12:50 UTC by rohanhc

2016-09-27 12:54 UTC, jishnu7 commented on android/KochavaPlugin.java
> +			logger.log("ROHAN Kochava meta " + meta.get("kochavaAppGUID"));
Hello Rohan Kochava!

2016-09-27 12:56 UTC, rampr commented on android/KochavaPlugin.java
> +	private Feature kTracker;
why are we using tabs or 4 spaces ?

2016-09-27 12:57 UTC, rohanhc commented on android/KochavaPlugin.java
> +			logger.log("ROHAN Kochava meta " + meta.get("kochavaAppGUID"));
Removing...

2016-09-27 12:57 UTC, rampr commented on android/KochavaPlugin.java
> +            kTracker.eventWithReceipt("Purchase", json, receiptObject);
indentation is wrong

2016-09-27 12:57 UTC, rohanhc commented on android/KochavaPlugin.java
> +	private Feature kTracker;
We use tabs in all .java files

2016-09-27 12:59 UTC, rohanhc commented on android/KochavaPlugin.java
> +            kTracker.eventWithReceipt("Purchase", json, receiptObject);
done

2016-09-27 12:59 UTC, rampr commented on js/index.js
> +  this.trackPurchase = function (uid, receipt, item, revenue,
Does iOS break because of this ?

2016-09-27 12:59 UTC, rohanhc commented on android/KochavaPlugin.java
> +			logger.log("ROHAN Kochava meta " + meta.get("kochavaAppGUID"));
done

2016-09-27 13:01 UTC, rampr commented on android/KochavaPlugin.java
> +		return true;
why are we doing this ?

2016-09-27 13:01 UTC, rampr commented on android/KochavaPlugin.java
> +	private Feature kTracker;
We should have a single convention in the whole repo.

2016-09-27 13:02 UTC, rampr commented on android/manifest.xml
> +<action android:name ="com.android.vending.INSTALL_REFERRER" />
indentation issues

2016-09-27 13:02 UTC, jishnu7 commented on android/KochavaPlugin.java
> +		return true;
needed to handle backbutton action

2016-09-27 13:03 UTC, rampr requested changes
Added comments against things that need to be changed.

2016-09-27 13:13 UTC, jishnu7 commented on android/KochavaPlugin.java
> +		} catch (JSONException ex) {
I don't think you need to pur the entire logic inside the try catch block.

2016-09-27 13:13 UTC, jishnu7 commented on android/KochavaPlugin.java
> +	private boolean DEBUG = true;
I thin you want this flag to be false by default, I guess.

2016-09-27 13:13 UTC, jishnu7 commented on android/manifest.xml
> +<action android:name ="com.android.vending.INSTALL_REFERRER" />
incorrect indent

2016-09-27 13:43 UTC, rohanhc commented on android/KochavaPlugin.java
> +	private boolean DEBUG = true;
done

2016-09-27 13:43 UTC, rohanhc commented on android/KochavaPlugin.java
> +		} catch (JSONException ex) {
done

2016-09-27 13:43 UTC, rohanhc commented on android/manifest.xml
> +<action android:name ="com.android.vending.INSTALL_REFERRER" />
done

2016-09-27 13:43 UTC, rohanhc commented on android/manifest.xml
> +<action android:name ="com.android.vending.INSTALL_REFERRER" />
done

2016-09-27 13:43 UTC, rohanhc commented on js/index.js
> +  this.trackPurchase = function (uid, receipt, item, revenue,
Doesn't look like it should

2016-09-27 13:45 UTC, jishnu7 approved these changes

2016-09-27 13:58 UTC, rampr commented on android/KochavaPlugin.java
> +	private Feature kTracker;
This is still there

2016-09-28 07:21 UTC, rampr commented
indentation is still 4 spaces, the whole repo should have the same style

2016-09-28 07:23 UTC, bijoshtj approved these changes

2016-09-28 07:24 UTC, rampr approved these changes

2016-09-28 07:25 UTC, merged